/*get all auto owners*/
-- SELECT
--   PER.*,
--   ADDR.*,
--   PASS.*,
--   L.*,
--   C.*
-- FROM PERSON PER
--   JOIN PASSPORT PASS ON PER.PASSPORT_ID = PASS.ID
--   JOIN ADDRESS ADDR ON PER.ADDRESS_ID = ADDR.ID
--   JOIN LICENCE L ON PER.LICENCE_ID
--   JOIN CAR C ON PER.ID = C.PERSON_ID

SELECT
  AO.*,
  A.*,
  P.*,
  L.*
FROM AUTOOWNER AO
  JOIN ADDRESS A ON AO.ADDRESS_ID = A.ID
  JOIN PASSPORT P ON AO.PASSPORT_ID = P.ID
  JOIN LICENCE L ON AO.LICENCE_ID = P.ID
WHERE AO.ID = 1;